# Generated by Django 3.1.5 on 2021-01-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Служебное поле')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Краткое описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ монитора')),
                ('display', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время работы от одного заряда аккумулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Служебное поле')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Краткое описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ монитора')),
                ('display', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение дисплея')),
                ('volume_ram', models.CharField(max_length=255, verbose_name='Объем встроенной памяти')),
                ('sd', models.BooleanField(default=True, verbose_name='Наличие SD карты')),
                ('sd_max_volume', models.CharField(max_length=255, verbose_name='Максимальный объем SD')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Разрешение основной камеры')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Разрешение фронтальной камеры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NotebookProduct',
        ),
    ]
